[general]
import = ["alacritty\\catppuccin-mocha.toml"]
working_directory = "C:\\Users\\acer"

[window]
startup_mode = "Maximized"

[font]
size = 10.3

[font.normal]
family = "Jetbrains Mono NL"
style = "Regular"

[selection]
save_to_clipboard = true

[cursor.style]
shape = "beam"
blinking = "never"

[terminal.shell]
program = "C:\\Windows\\System32\\cmd.exe"
args = ["/c", "C:\\Users\\acer\\AppData\\Roaming\\alacritty\\vsbash.bat"]

[[keyboard.bindings]]
key = "PageUp"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollLineDown"
