[general]
import = ["alacritty\\catppuccin-mocha.toml"]
working_directory = "C:\\Users\\acer"

[window]
startup_mode = "Maximized"

[font]
size = 12

[font.normal]
family = "Iosevka Term"
style = "Medium"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "C:\\Windows\\System32\\cmd.exe"
args = ["/c", "C:\\Users\\acer\\AppData\\Roaming\\alacritty\\vsbash.bat"]

[[keyboard.bindings]]
key = "PageUp"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollLineDown"
